- .github/workflows/cli-test-from-precompiled-binaries.yaml
- .github/workflows/cli-test-from-sources.yaml
- .github/workflows/cli_test_run.yaml
- .gitignore
- README.md
- src/tests/cli-tests/jest.config.js
- src/tests/cli-tests/package-lock.json
- src/tests/cli-tests/package.json
- src/tests/cli-tests/src/contracts/solidity/contract.sol
- src/tests/cli-tests/src/contracts/yul/contract.yul
- src/tests/cli-tests/src/contracts/zkasm/contract.zkasm
- src/tests/cli-tests/src/entities.ts
- src/tests/cli-tests/src/helper.ts
- src/tests/cli-tests/tests/asm.test.ts
- src/tests/cli-tests/tests/common.test.ts
- src/tests/cli-tests/tests/yul.test.ts
- src/tests/cli-tests/tests/zkasm.test.ts
- src/tests/cli-tests/tsconfig.json
Initial proof of concept (POC) test solution for zksolc cli.
To test CLI output
> test: poc test solution for zksolc

- cli-tests/src/contracts/llvm/contract.ll
- cli-tests/src/entities.ts
- cli-tests/tests/llvm.test.ts
Implemented set of test cases for llvm-ir mode.
To increase test coverage.
> test: llvm-ir automation test coverage

- cli-tests/tests/combined-json.test.ts
combined-json tests
cover --combined-json option
- [-] Documentation comments have been added / updated.
> test: combined-json tests

- cli-tests/src/contracts/json/contract.json
- cli-tests/src/entities.ts
- cli-tests/tests/metadata-hash.test.ts
- cli-tests/tests/optimization.test.ts
- cli-tests/tests/standard-json.test.ts
test for:
tests/metadata-hash.test.ts
tests/optimization.test.ts
tests/standard-json.test.ts -- temporary excluded due to CPR-1409
> test: test for metadata, optimization, standard-json

- cli-tests/src/entities.ts
- cli-tests/tests/libraries.test.ts
- cli-tests/tests/missing-lib.test.ts
Tests for libraries options
--libraries & --detect-missing-library
> test: add tests for libraries and detect-missing-library options

- cli-tests/src/entities.ts
- cli-tests/src/helper.ts
- cli-tests/tests/output-dir.test.ts
Automation tests for next test cases:
Increase automation test coverage.
> test: --output-dir automation tests

- cli-tests/src/entities.ts
- cli-tests/tests/solc.test.ts
> test: add tests with --solc

- Cargo.lock
Update dependencies to pull the newest changes from era-zkEVM-assembly.
These changes include assembler support for jump tables.
> Pull changes from era-zkEVM-assembly

- .github/actions/cli-tests/action.yml
- cli-tests/package-lock.json
- cli-tests/package.json
- cli-tests/src/entities.ts
- cli-tests/src/helper.ts
- cli-tests/tests/common.test.ts
- cli-tests/tests/output-dir.test.ts
- cli-tests/tests/solc.test.ts
Fix conflict in tests for parallel run
> test: fix parallel test run

- src/zksolc/arguments.rs
Prints help if no arguments are provided.
To make behavior similar to `solc`.
> Print help if no arguments are provided

- CHANGELOG.md
- src/lib.rs
- src/solc/mod.rs
- src/zksolc/main.rs
Fixes the broken pipe error.
It is now possible to redirect the process output to another process.
> fix: the broken pipe error

- .github/actions/cli-tests/action.yml
- .github/workflows/test-cli.yaml
- cli-tests/src/helper.ts
- cli-tests/tests/common.test.ts
- cli-tests/tests/libraries.test.ts
- cli-tests/tests/output-dir.test.ts
- cli-tests/tests/standard-json.test.ts
Fix for e2e tests + fix from https://github.com/matter-labs/era-compiler-solidity/pull/28
> test: fix e2e tests

- .cargo/config.toml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- LLVM.lock
- src/evmla/assembly/instruction/codecopy.rs
- src/evmla/assembly/instruction/jump.rs
- src/evmla/assembly/instruction/stack.rs
- src/evmla/ethereal_ir/entry_link.rs
- src/evmla/ethereal_ir/function/block/element/mod.rs
- src/evmla/ethereal_ir/function/mod.rs
- src/yul/parser/statement/assignment.rs
- src/yul/parser/statement/block.rs
- src/yul/parser/statement/expression/function_call/mod.rs
- src/yul/parser/statement/expression/function_call/verbatim.rs
- src/yul/parser/statement/expression/mod.rs
- src/yul/parser/statement/for_loop.rs
- src/yul/parser/statement/function_definition.rs
- src/yul/parser/statement/if_conditional.rs
- src/yul/parser/statement/switch/mod.rs
- src/yul/parser/statement/variable_declaration.rs
> Update to LLVM 17

- .github/workflows/build_release.yaml
- .github/workflows/test-cli.yaml
- .github/workflows/test.yaml
Updates CI to use llvm17 docker image.
Aligning docker and project versions.
> ci: update to use llvm17 docker image

- .github/actions/build-llvm/action.yml
- .github/actions/cli-tests/action.yml
- .github/actions/unit-tests/action.yml
- .github/workflows/build_release.yaml
- .github/workflows/test-cli.yaml
- .github/workflows/test.yaml
Use the new LLVM builder with `--target-env` option + small CI fixes.
To get the latest builder from cargo, facilitate its updates in the future, and simplify CI.
> ci: use new llvm builder

- CONTRIBUTING.md
- README.md
- src/solc/standard_json/output/error/mod.rs
- src/yul/parser/statement/expression/function_call/name.rs
Fixes README.md after LLVM 17 and builder updates:
To fix documentation issues.
> docs: update setup and build instructions

- .github/actions/build-llvm/action.yml
Update llvm builder to 1.0.25 (renaming from zkevm-llvm to zksync-llvm).
To fix musl download issue and correspond to the latest naming conventions requirements.
> ci: update llvm builder to 1.0.25

- .github/workflows/test.yaml
A proper fix for changed files condition.
> ci: fix changed files condition

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/evmla/ethereal_ir/function/block/element/mod.rs
- src/tests/unsupported_opcodes.rs
- src/yul/parser/statement/expression/function_call/mod.rs
Adds the EXTCODECOPY support.
Such precompile was added to System Contracts.
> feat: support EXTCODECOPY

- CHANGELOG.md
- Cargo.lock
- src/process/input_eravm.rs
- src/process/input_evm.rs
- src/process/mod.rs
- src/project/mod.rs
1. Optimizes the RAM usage while running recursive child processes of itself.
2. Includes an LLVM fix for the GVN/NewGVN optimizer pass.
The RAM usage with large projects was over the top and caused OOM.
> fix: optimize RAM usage

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- cli-tests/tests/solc.test.ts
Add advanced cargo checks: `fmt`, `clippy`, `udeps` (unused dependencies), `audit`
Additionally:
* Fix CLI test issue
* Remove unused `colored` dependency found by `udeps`
Related to:
* [CPR-1738](https://linear.app/matterlabs/issue/CPR-1738/add-cargo-fmt-and-cargo-clippy-to-rust-repos)
* [CPR-1301](https://linear.app/matterlabs/issue/CPR-1301/static-analysis-for-rust-projects)
> ci: add advanced cargo checks fmt, clippy, udeps and audit

- CONTRIBUTING.md
- README.md
> docs: fix documentation links after update

- .github/workflows/release.yaml
Add -gnu in the windows executable suffix
To align with plugins.
> chore: add -gnu in the windows executable suffix

- src/zksolc/arguments.rs
Update the `--threads` parameter description.
To fix the wrong info about concurrent tests in the desc.
> docs: update --threads parameter description

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- LLVM.lock
- README.md
- era-compiler-solidity/src/evmla/ethereal_ir/function/block/element/stack/element.rs
> release: v1.5.3

- .github/workflows/dependencies.yaml
Update dependencies verification workflow with:
Tested in `era-compiler-common`:
https://github.com/matter-labs/era-compiler-common/actions/runs/10717531440/job/29717419792
To allow testing in dependency repositories flawlessly.
> ci: update depencencies verification workflow

- .github/workflows/sanitizers.yaml
- .github/workflows/test.yaml
Run unit tests for release and debug modes.
To catch errors in optimized and not-optimized builds.
> ci: run unit tests for release and debug modes

- CHANGELOG.md
- LLVM.lock
> release: v1.5.4

- .github/workflows/dependencies.yaml
Align LLVM build in dependencies workflow with the test workflow.
To build LLVM with assertions and `RelWithDebInfo` as in the test.
> ci: fix dependencies workflow llvm build

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- era-compiler-solidity/src/zksolc/main.rs
- era-compiler-solidity/tests/cli/basic.rs
- era-compiler-solidity/tests/cli/mod.rs
- era-compiler-solidity/tests/examples/contracts/broken.bad
Fixes the pipeline without output parameters.
It was not run if no output was requested, and the input was not validated.
> fix: the pipeline without output parameters

- .github/workflows/dependencies.yaml
Fixes crate name for `llvm-sys` dependency.
To fix failure in dependency definition for `llvm-sys` https://github.com/matter-labs/era-compiler-solidity/actions/runs/11054727456/job/30712206141
> ci: fix dependencies workflow llvm-sys dependency

- CHANGELOG.md
- era-compiler-solidity/src/solc/mod.rs
- era-compiler-solidity/tests/solc-bin.json
Adds the support for solc v0.8.28.
> feat: support solc v0.8.28

- CHANGELOG.md
- era-compiler-solidity/src/solc/mod.rs
> release: v1.5.5

- LLVM.lock
> fix: update LLVM.lock

- .github/workflows/deploy-docs.yaml
Fix typo `tag` => `TAG` in mdbook URL download.
> ci: fix typo in mdbook URL download

- docs/01-installation.md
1. Fixed formatting in some cases and makes line breaks more consistent (we should be relying on IDEs word wrapping).
2. Removed a few duplicates of *solc* installation instructions and tips.
3. Renamed `LLVM_SYS_{version}_PREFIX` to `LLVM_SYS_170_PREFIX`, as our doc builds are going to be versioned.
4. Moved more sentences to *important/tip/warning* blocks.
5. Added more detail here and there.
6. Brought back `must` instead of `should` is some cases. I believe our docs must be confident!
7. Made full stops and semicolons more consistent.
8. Brought back `artifacts produced by solc`. I believe it describes zksolc-solc relationship with higher precision.
> docs: provide suggestions to sayon's suggestions

- .github/workflows/check-hardhat.yaml
Check that `hardhat` examples are working with each release.
Also, add capability to trigger this workflow manually.
To make sure hardhat integration is working with the new release versions.
> ci: check hardhat integration with each release

- .github/workflows/deploy-docs.yaml
- README.md
- docs/README.md
To give instructions on how to build docs locally and unify deployments across the repositories.
> docs: add mdbook readme and common CI to release mdbooks

- .github/workflows/deploy-docs.yaml
- .github/workflows/test.yaml
Add common mandatory required CI check.
To be able to use the automatic merge feature with making sure CI is passed.
> ci: add common mandatory required check

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- LLVM.lock
> release: version 1.5.7

- .github/workflows/secrets-scanner.yaml
- .github/workflows/test.yaml
Fix required TruffleHog check.
Until we find and merge proper solution for devops, use hardcoded TruffleHog job and name.
> ci: fix required TruffleHog check

- .github/workflows/deploy-docs.yaml
- docs/src/SUMMARY.md
- docs/src/guides/01-sanitizers.md
Add guide on how to build `zksolc` with sanitizers enabled.
> docs: add guide on how to build with sanitizers enabled

- .github/workflows/check-hardhat.yaml
Add Foundry check with each release.
To check that Foundry is not broken with each compiler release.
> ci: add foundry check with each zksolc release

- .github/workflows/ccache-regen.yaml
Regenerate and save Rust cache daily.
To speed up cargo checks and execution of unit tests in PRs.
> ci: regenerate rust cache daily in addition to llvm

- docs/src/02-command-line-interface.md
- docs/src/04-combined-json.md
- docs/src/05-linker.md
- docs/src/guides/01-sanitizers.md
- era-compiler-solidity/src/build_eravm/mod.rs
- era-compiler-solidity/src/build_evm/mod.rs
- era-compiler-solidity/src/zksolc/arguments.rs
- era-compiler-solidity/src/zksolc/main.rs
- era-compiler-solidity/tests/cli/llvm_ir.rs
- era-compiler-solidity/tests/common/const.rs
- era-compiler-solidity/tests/data/contracts/llvm_ir/LinkerError.ll
- era-solc/src/standard_json/output/error/collectable.rs
- era-solc/src/standard_json/output/mod.rs
Documents remaining CLI endpoints. Covers a few more missing lines of code.
> docs: remaining CLI endpoints

- docs/src/02-command-line-interface.md
> fix: a few improvements for docs

- CHANGELOG.md
- docs/src/01-installation.md
- docs/src/02-command-line-interface.md
- docs/src/06-eravm-extensions.md
- docs/src/SUMMARY.md
- era-compiler-solidity/src/yul/parser/statement/expression/function_call/verbatim.rs
- era-yul/src/yul/parser/statement/expression/function_call/name.rs
Documents EraVM call simulations and verbatim.
> docs: EraVM call simulations and verbatim

- CHANGELOG.md
- Cargo.lock
- LLVM.lock
- README.md
Tests the v1.5.8 release build.
> release: v1.5.8

- .github/workflows/release.yaml
Fix llvm version check in release workflow.
> ci: fix llvm version check in release workflow

- docs/js/version-box.js
Fix versions sorting order.
To `latest` go first, then from latest release to oldest.
> docs: fix versions sorting order

- docs/src/01-installation.md
Documents the ZKsync fork of solc in more detail.
> docs: add more info on ZKsync fork of solc

- .github/workflows/release.yaml
Disable prerelease and mark the new release as the `latest`.
> ci: disable prerelease and mark new release as latest

- docs/js/version-box.js
This PR updates the `version-box.js` file to use more optimized JavaScript code.
This PR should make the overall execution of this file faster and more robust, improving the documentation in general.
- [/] Tests for the changes have been added / updated.
- [/] Documentation comments have been added / updated.
- [/] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.
> docs: optimize `version-box.js`

- docs/js/version-box.js
This PR updates the `version-box.js` file to use more optimized JavaScript code.
This PR should make the overall execution of this file faster and more robust, improving the documentation in general.
- [/] Tests for the changes have been added / updated.
- [/] Documentation comments have been added / updated.
- [/] Code has been formatted via `cargo fmt` and checked with `cargo clippy`.
> docs: optimize `version-box.js` (#238)

- CHANGELOG.md
- era-compiler-solidity/src/build_eravm/mod.rs
- era-compiler-solidity/src/build_evm/mod.rs
- era-compiler-solidity/src/project/contract/ir/yul.rs
- era-compiler-solidity/src/project/mod.rs
- era-compiler-solidity/tests/cli/output_dir.rs
- era-compiler-solidity/tests/data/contracts/yul/Test.yul
- era-compiler-solidity/tests/data/standard_json_input/yul_solc.json
- era-compiler-solidity/tests/unit/combined_json.rs
- era-compiler-solidity/tests/unit/standard_json.rs
Fixes https://github.com/matter-labs/era-compiler-solidity/issues/243.
> fix: Yul contract names in standard JSON output

- era-compiler-solidity/src/process/mod.rs
- era-compiler-solidity/src/zksolc/arguments.rs
> chore: fix some typos in comment

- Cargo.lock
- era-compiler-solidity/src/lib.rs
- era-compiler-solidity/src/project/contract/mod.rs
- era-compiler-solidity/src/project/mod.rs
- era-compiler-solidity/tests/common/mod.rs
- era-compiler-solidity/tests/unit/libraries.rs
- era-solc/src/standard_json/input/settings/libraries.rs
Fixes https://github.com/matter-labs/era-compiler-solidity/issues/257
> fix(eravm): missing libraries filtering

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- LLVM.lock
> release: v1.5.11

- era-compiler-solidity/src/const.rs
- era-compiler-solidity/src/evmla/assembly/mod.rs
- era-compiler-solidity/src/evmla/ethereal_ir/function/block/element/mod.rs
- era-compiler-solidity/src/lib.rs
- era-compiler-solidity/src/project/contract/ir/evmla.rs
- era-compiler-solidity/src/project/contract/mod.rs
- era-compiler-solidity/src/zksolc/arguments.rs
- era-compiler-solidity/src/zksolc/main.rs
- era-solc/src/solc.rs
Fixes a couple of EVMLA infinite loop occasions,
> fix(evm): a couple of EVMLA infinite loop occasions

- .github/workflows/dependencies.yaml
- Cargo.lock
- era-compiler-solidity/Cargo.toml
Fix dependency workflow.
Rework using `workflow_call` instead of `workflow_dispatch` to not require any private token, make things more secure.
> ci: fix dependency workflow

- era-compiler-solidity/src/evmla/assembly/instruction/codecopy.rs
- era-compiler-solidity/src/evmla/ethereal_ir/function/block/element/mod.rs
Translates EVMLA `PUSH data` to a loop of `mstore` to the heap.
solc uses `CODECOPY` for it in EVMLA codegen, probably by keeping these blobs somewhere between deploy and runtime code. Later we can investigate whether this approach will give us any improvements.
> feat(evm): codecopy data blobs directly to heap

- Cargo.lock
- era-compiler-solidity/src/evmla/ethereal_ir/function/block/element/mod.rs
- era-compiler-solidity/src/yul/parser/statement/expression/function_call/mod.rs
Supports the transient storage in the EVM target.
> feat(evm): transient storage

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/src/02-command-line-interface.md
- era-compiler-solidity/tests/unit/messages.rs
- era-solc/src/standard_json/input/settings/error_type.rs
- era-solc/src/standard_json/output/error/mod.rs
- era-solc/src/standard_json/output/source.rs
- rust-toolchain.toml
Fixes https://github.com/matter-labs/era-compiler-solidity/issues/275
> feat(eravm): add an AST error for ripemd160

- docs/src/03-standard-json.md
Improves clarity in a couple of places.
> fix: several wordings in standard JSON doc

- CHANGELOG.md
- era-compiler-solidity/src/lib.rs
- era-compiler-solidity/tests/cli/combined_json.rs
- era-compiler-solidity/tests/common/mod.rs
- era-solc/src/combined_json/selector.rs
- era-solc/src/solc.rs
- era-solc/src/standard_json/output/error/mapped_location.rs
Fixes https://github.com/matter-labs/era-compiler-solidity/issues/279
> fix: missing --via-ir flag in combined json request to solc

- Cargo.lock
- README.md
- era-compiler-solidity/src/evmla/assembly/mod.rs
- era-compiler-solidity/src/evmla/ethereal_ir/function/block/element/mod.rs
Supports more instructions in EVMLA:
1. `PUSHDEPLOYADDRESS`
2. `PUSH_Data`
> feat: push deploy address and blob data

- LLVM.lock
> release: v1.5.12

- .cargo/config.toml
- .github/workflows/ccache-regen.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
- .gitmodules
- CHANGELOG.md
- Cargo.lock
- README.md
- docs/src/01-installation.md
- era-compiler-solidity/Cargo.toml
- era-compiler-solidity/src/project/contract/mod.rs
- era-compiler-solidity/src/yul/parser/statement/expression/function_call/mod.rs
- era-solc/src/standard_json/output/source.rs
- rust-toolchain.toml
> feat: update to LLVM 19

- .gitmodules
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> chore: release v1.5.15
