- Cargo.lock
- Cargo.toml
- src/yul/parser/statement/function_definition.rs
Adds `optnone` and `noinline` attributes to all functions if middle-end optimizations are disabled.
It should disable some RAM-demanding LLVM passes which cause OOM on large unoptimized codebases.
> Add noinline+optnone attributes in M0

- .github/workflows/unit-tests.yaml
Fixes [CPR-1274](https://linear.app/matterlabs/issue/CPR-1274/github-action-for-zksolc-unit-tests)
Add unit tests execution in CI with each PR and merge to the trunk.
Supported targets:
* Macos x86_64
* Macos ARM64
* Linux x86_64
* Linux ARM64
* Windows Mingw64
Results are reported as PR checks, e.g.:
As well as PR auto-updated comments:
In order to keep the trunk always stable, introduce unit tests quality gates on the PR level as well as make sure that unit tests in the `main` branch are always working after the merge.
> ci: add unit tests workflow

- .github/workflows/build_release.yaml
- .github/workflows/cli-test-from-sources.yaml
- .github/workflows/unit-tests.yaml
Update Linux docker image to `ubuntu22-llvm15-latest` from public Dockerhub registry.
The previous `jammy` image was private preventing forks to be properly tested.
> ci: update linux docker image to public ubuntu22-llvm15-latest

- Cargo.lock
- Cargo.toml
Updates zkVM deps to v1.4.1.
It is needed to run the CI and then update all compilers to zkVM v1.4.1.
> Update to zkVM v1.4.1

- .github/workflows/unit-tests.yaml
Fix CI unit tests results parsing error caused by `lxml` libraries on MacOS ARM64 host:
```
dlopen(/Users/hetzner/actions-runner/_work/era-compiler-solidity/era-compiler-solidity/enricomi-publish-action-venv/lib/python3.8/site-packages/lxml/etree.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (_exsltDateXpathCtxtRegister)
```
The fix for now is to use the previous action version before `lxml` was updated to `5.1.0` causing these issues on MacOS ARM64 hosts.
To restore unit tests and CI checks back to normal.
> ci: fix unit tests results parsing for macos arm64

- README.md
fix broken links in documentation caused by code base renaming.
> fix: broken links in documentation caused by code base renaming

- .github/workflows/build_release.yaml
Restores proper sending of Slack notifications about new releases after [ITS-392](https://linear.app/matterlabs/issue/ITS-392/slack-webhook-for-compilers-repositories) fix.
To notify the other teams about new `zksolc` releases.
> ci: restore slack notifications with new token

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/yul/parser/statement/expression/function_call/mod.rs
- src/yul/parser/statement/expression/function_call/verbatim.rs
Adds a simulation to swap active pointers.
We are allowing 16 saved pointers now, where 0th will be the active one.
> Support swapping 16 active pointers

- .github/actions/build-llvm/action.yml
CI: `apt update` is required for docker container jobs to install `ccache` properly. See [here](https://github.com/hendrikmuhs/ccache-action?tab=readme-ov-file#usage).
Fixing CI failures.
It worked before because the Docker container was not standardized, but after cleaning it up, this is required now.
> ci: fix ccache installation on Linux with new docker

- src/lib.rs
- src/zksolc/main.rs
Checks for the `solc` binary only in Solidity/Yul modes.
The `solc` binary was checked even in `--zkasm` mode.
> Validate solc only for Solidity/Yul input

- cli-tests/tests/standard-json.test.ts
Added negative --standard-json test with an incompatible input format
> test: added test 1828

- CHANGELOG.md
- src/solc/mod.rs
Updates the Solidity tests for solc v0.8.25.
solc v0.8.25 has been released.
> Update for solc v0.8.25

- CHANGELOG.md
- src/const.rs
- src/evmla/assembly/instruction/name.rs
- src/evmla/ethereal_ir/function/mod.rs
- src/lib.rs
- src/project/contract/ir/evmla.rs
- src/project/contract/ir/llvm_ir.rs
- src/project/contract/ir/mod.rs
- src/project/contract/ir/zkasm.rs
- src/solc/pipeline.rs
- src/solc/standard_json/input/mod.rs
- src/solc/standard_json/input/settings/selection/file/flag.rs
- src/yul/lexer/mod.rs
- src/yul/lexer/token/lexeme/comment/mod.rs
- src/zksolc/arguments.rs
Adds files from --libraries to input sources.
Unlike `solc`, `zksolc` used to not to include these files to inputs, so `Source code for library X.sol` errors were emitted.
> bug: add files from --libraries to sources

- .github/actions/install-solc/action.yml
- .github/workflows/test-cli.yaml
- .github/workflows/test.yaml
- CHANGELOG.md
- src/build_eravm/contract.rs
- src/build_evm/contract.rs
- src/solc/combined_json/mod.rs
Missing `--overwrite` now returns an error.
Earlier, it would print an error and return exit code 0.
> Missing `--overwrite` now returns an error

- .github/pull_request_template.md
- CHANGELOG.md
- src/build_eravm/contract.rs
- src/build_evm/contract.rs
- src/solc/combined_json/mod.rs
Prints bytecode to --output-dir as a hex string.
Binary format that was printed before, was unreadable and unusable by the tools.
> Print bytecode to --output-dir as a hex string

- cli-tests/src/helper.ts
- cli-tests/tests/common.test.ts
> test: test shows the issue-difference in the bin output

- cli-tests/tests/output-dir.test.ts
Uncommented test step id1812 "solc exit code == zksolc exit code" 
This case works well on **win** and **osx** on CI. For **linux** locally I see an error that is expected because we cannot write to Read Only directory. But on CI compiler finish with exit code 0 that is unexpected for this case. That if why we use `if (os.platform() !== 'linux') {}`
it returns different exit codes
> test: compare exit codes for output-dir with ro permission

- .cargo/config.toml
- .github/actions/build-llvm/action.yml
- .github/actions/build/action.yml
- .github/actions/cli-tests/action.yml
- .github/actions/unit-tests/action.yml
- .github/workflows/build_release.yaml
- .github/workflows/test-cli.yaml
- .github/workflows/test.yaml
- Cargo.toml
- build.rs
Fixes [CPR-1581](https://linear.app/matterlabs/issue/CPR-1581/undocumented-additional-zksolczkvyper-cross-compile-build-options)
Removes the necessity to add additional `RUSTFLAGS` for Linux Musl builds (`"-C link-arg=-Wl,-Bstatic -C link-arg=-lc -C link-arg=-L/usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/ -C link-arg=-lclang_rt.builtins-aarch64"`).
Instead of using prebuilt system builtins (supported by https://github.com/matter-labs/era-compiler-llvm-builder/pull/26), we now use builtins from our host compiler built for stage 1. Additionally, we use `lld` linker.
To unify builds across all targets and be independent from clang installation on the host system that we do not control.
> build: proper crt builtins linkage for aarch64-unknown-linux-musl

- .cargo/config.toml
- Cargo.toml
Use an unique name for compiler-rt links for `aarch64-unknown-linux-arm` target.
To solve the linkage issue when both `zksolc` and `zkvyper` are used as a dependency.
> build: use unique name for crt links

- src/solc/standard_json/input/mod.rs
Removes the parallel iterator when the project is created from a list of strings.
1. The iterator has been causing data races in unit tests.
2. It is certainly redundant when collecting strings into a map.
> fix: the culprit of data race in unit tests

- .github/workflows/test.yaml
Fixes `push` trigger issue with tests.
Checkout depth is required for changed files to work with `push` trigger. For more info, see: https://github.com/tj-actions/changed-files/tree/v44/?tab=readme-ov-file#on-push-%EF%B8%8F
> ci: fix push trigger issue

- .github/workflows/test.yaml
Try to skip checkout for changed files to fix `push` trigger issue.
> ci: skip initial fetch for changed files

- src/solc/mod.rs
Makes the `solc` version parser more flexible.
We're fixing the devops mistake where `0.8.25-1.0.0` format is written as the ZKsync revision of `solc` instead of simply `1.0.0`.
Both new and old formats will be accepted.
> fix: support one-part format of the ZKsync version of solc

- src/lib.rs
- src/project/mod.rs
- src/solc/mod.rs
- src/solc/standard_json/input/mod.rs
- src/solc/standard_json/input/settings/mod.rs
- src/solc/standard_json/input/settings/optimizer/mod.rs
- src/solc/standard_json/input/settings/selection/file/flag.rs
- src/solc/standard_json/input/settings/selection/file/mod.rs
- src/solc/standard_json/input/settings/selection/mod.rs
- src/solc/standard_json/input/source.rs
- src/tests/mod.rs
- src/tests/standard_json.rs
1. Optimizes Yul validation with `solc` by using only one standard JSON request.
2. Add unit tests for all cases.
1. Previously, a `solc --strict-assembly <file>` was used for each file.
2. Unit tests for `solc` validation were missing.
> feat: optimize Yul validation and add more unit tests

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/process/mod.rs
- src/project/mod.rs
- src/solc/mod.rs
- src/solc/version.rs
- src/tests/mod.rs
- src/tests/standard_json.rs
- src/zksolc/main.rs
Makes `solc` a singleton, initializing it and requesting `version` only once.
It must reduce the number of spawned child processes, improving the general performance.
> feat: make solc a singleton

- src/process/mod.rs
- src/solc/mod.rs
Reads child process data in another thread.
It should help with the excessive RAM usage in `solc`, which probably collects all its output before `zksolc` starts reading it.
> feat: read child process output in another thread

- .github/actions/install-solc/action.yml
- .github/workflows/test.yaml
- CHANGELOG.md
- src/solc/mod.rs
Adds support for solc v0.8.26.
solc v0.8.26 has been released.
> feat: support solc v0.8.26

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli-tests/tests/eravm-assembly.test.ts
- cli-tests/tests/llvm-ir.test.ts
- cli-tests/tests/yul.test.ts
- src/evmla/assembly/instruction/jump.rs
- src/evmla/assembly/mod.rs
- src/evmla/ethereal_ir/function/block/element/mod.rs
- src/evmla/ethereal_ir/function/block/element/stack/mod.rs
- src/evmla/ethereal_ir/function/mod.rs
- src/lib.rs
- src/process/input_eravm.rs
- src/process/input_evm.rs
- src/process/mod.rs
- src/project/contract/metadata.rs
- src/project/contract/mod.rs
- src/project/mod.rs
- src/solc/combined_json/mod.rs
- src/solc/mod.rs
- src/solc/standard_json/input/mod.rs
- src/solc/standard_json/input/source.rs
- src/tests/mod.rs
- src/yul/parser/statement/block.rs
- src/yul/parser/statement/expression/function_call/mod.rs
- src/yul/parser/statement/variable_declaration.rs
- src/zksolc/arguments.rs
- src/zksolc/main.rs
Allows passing arbitrary LLVM arguments in FE.
It is needed for experiments with the optimizer, and for debugging.
> feat: pass arbitrary options to LLVM

- .github/workflows/release.yaml
Dynamically create a build/release matrix instead of skipping steps.
* [Test with all jobs](https://github.com/matter-labs/era-compiler-solidity/actions/runs/9404090795)
* [Test with 3 jobs](https://github.com/matter-labs/era-compiler-solidity/actions/runs/9403863106)
* [Test with no jobs](https://github.com/matter-labs/era-compiler-solidity/actions/runs/9404092693)
This will not overload runners just to skip all steps and speed up builds.
Related to [CPR-1733](https://linear.app/matterlabs/issue/CPR-1733/improve-zksolczkvyper-matrix-jobs-to-disable-completely-if-the)
> ci: add proper matrix configuration when platforms are off

- .github/workflows/release.yaml
Fixes an issue with release generation if `ref` is not specified.
GH API cannot take short sha for commit.
> ci: fix release issue with empty ref parameter

- .github/actions/build/action.yml
- .github/workflows/release.yaml
Related to [CPR-1379](https://linear.app/matterlabs/issue/CPR-1739/fix-the-changelog-publishing)
There always can be some unexpected special symbols in the changelog that are impossible to filter or escape properly while manually creating the Slack notification from the changelog entry This PR is a proposal to never do this, and instead use GitHub <--> Slack integration to subscribe to the `releases` in the repository forwarding the required release notification in the common group when the release is out and verified.
> ci: fix release with special symbols in changelog

- src/build_eravm/mod.rs
- src/build_evm/mod.rs
- src/lib.rs
- src/solc/standard_json/output/error/collectable.rs
- src/solc/standard_json/output/error/mod.rs
- src/solc/standard_json/output/mod.rs
- src/tests/mod.rs
Moves common solc error handling code to a trait.
> chore: move common error handling code to a trait

- CHANGELOG.md
- src/lib.rs
- src/message_type.rs
- src/solc/mod.rs
- src/solc/standard_json/input/mod.rs
- src/solc/standard_json/output/error/mod.rs
- src/solc/standard_json/output/mod.rs
- src/solc/standard_json/output/source.rs
- src/tests/messages.rs
- src/tests/mod.rs
- src/zksolc/arguments.rs
- src/zksolc/main.rs
1. Removed obsolete warnings for `ecrecover` and `extcodesize`.
2. `send`/`transfer` now trigger an error with ZKsync edition of solc.
3. Added the `suppress-errors` parameter to suppress the error above.
> feat: remove obsolete warnings

- CHANGELOG.md
- src/build_eravm/contract.rs
- src/build_evm/contract.rs
- src/message_type.rs
- src/process/mod.rs
- src/solc/mod.rs
- src/solc/standard_json/input/mod.rs
- src/solc/standard_json/input/settings/metadata.rs
- src/solc/standard_json/input/source.rs
- src/solc/standard_json/output/error/mapped_location.rs
- src/solc/standard_json/output/error/mod.rs
- src/solc/standard_json/output/mod.rs
- src/solc/standard_json/output/source.rs
- src/tests/messages.rs
- src/yul/error.rs
1. Removes ASCII boxes from compiler messages.
2. Fixes broken standard JSON I/O with solc 0.5.x due to unsupported `bytecodeHash` field.
3. Fixes the issue when warnings were sometimes printed twice.
4. Fixes warnings for `origin()` in assembly that were not emitted for solc 0.5 and older.
1. They sometimes break formatting and require a lot of work to fix it. Our warnings are not that critical anymore, whereas critical ones have been converted to errors.
> chore: remove ASCII boxes

- .github/actions/build/action.yml
- .github/actions/unit-tests/action.yml
- .github/workflows/sanitizers.yaml
Support builds and unit tests run with sanitizers:
* As per request triggered manually from [actions page](https://github.com/matter-labs/era-compiler-solidity/actions/workflows/sanitizers.yaml)
* Weekly with address sanitizer
[Testing workflow](https://github.com/matter-labs/era-compiler-solidity/actions/runs/9680376340/job/26708389798?pr=110)
To add a capability to find more bugs using sanitizers.
> ci: support unit tests with sanitizers

- Cargo.lock
- Cargo.toml
- src/evmla/assembly/instruction/jump.rs
- src/evmla/assembly/instruction/mod.rs
- src/evmla/assembly/instruction/name.rs
- src/evmla/ethereal_ir/function/block/element/stack/mod.rs
- src/evmla/ethereal_ir/function/block/mod.rs
- src/evmla/ethereal_ir/function/visited_element.rs
Replaces md5 with keccak256 in the EVM assembly translator.
md5 is shorter and worse.
> fix: replace md5 with keccak256

- .github/workflows/release.yaml
Add support for universal MacOS binary (x64 + arm64). For now, it is added additionally to existing arm64 and amd64 binaries.
[Testing workflow](https://github.com/matter-labs/era-compiler-solidity/actions/runs/9741681761)
> release: support universal macosx binary

- .github/workflows/release.yaml
Add version guard that cargo package, created tag, and version in changelog must be equal when releasing.
[Testing workflow](https://github.com/matter-labs/era-compiler-solidity/actions/runs/9839561820/job/27162678159)
To prevent discrepancies between `--version` output and releases.
> release: add version guard between cargo, tag and changelog

- .github/actions/build/action.yml
- .github/actions/unit-tests/action.yml
- .github/workflows/release.yaml
- .github/workflows/sanitizers.yaml
- .github/workflows/test.yaml
- Cargo.lock
Support Linux GNU targets in addition to Musl ones:
* Two new targets `*-unknown-linux-gnu` to be tested
* Two new static binaries will be generated in the release with `*-linux-gnu` suffix.
To simplify and deprecate heavy and slow Musl targets in the future.
> ci: support static gnu binaries

- .github/actions/build/action.yml
- .github/actions/unit-tests/action.yml
- .github/workflows/test.yaml
To monitor and improve code coverage for unit tests over time.
> ci: add code coverage support with codecov

- .github/actions/build/action.yml
Disable static libc when running with sanitizers.
Static libc is incompatible with sanitizers run.
[Testing workflow with sanitizers](https://github.com/matter-labs/era-compiler-solidity/actions/runs/10307324378)
> ci: fix sanitizers incompatibility with static libc

- codecov.yml
Disable explicit coverage checks that can fail CI.
For now, coverage is only for informational purposes.
> ci: do not fail code coverage checks if coverage drops

- README.md
* Update ReadMe now that musl is not needed.
* Note support for Linux ARM64.
* Harmonize case for musl and ARM64.
> docs: Update ReadMe now that musl is not needed; support Linux ARM64 

- README.md
* “your `LLVM_SYS_170_PREFIX`” was not sufficiently explained in the ReadMe.
Copied, with one phrasing tweak, from https://github.com/matter-labs/era-compiler-vyper/pull/90.
> docs: Explain LLVM_SYS_170_PREFIX and tweak phrasing, from zkvyper PR#90.

- Cargo.lock
- src/zksolc/arguments.rs
- src/zksolc/main.rs
Sets the `noinline` attribute for all calls in `-O0`.
It will prevent inlining of some runtime functions with `alwaysinline` attribute.
> feat: set noinline attribute for all calls in -O0

- era-compiler-solidity/tests/cli/asm.rs
- era-compiler-solidity/tests/cli/basic.rs
- era-compiler-solidity/tests/cli/bin.rs
- era-compiler-solidity/tests/cli/combined_json.rs
- era-compiler-solidity/tests/cli/eravm_assembly.rs
- era-compiler-solidity/tests/cli/libraries.rs
- era-compiler-solidity/tests/cli/llvm_ir.rs
- era-compiler-solidity/tests/cli/metadata_hash.rs
- era-compiler-solidity/tests/cli/missing_lib.rs
- era-compiler-solidity/tests/cli/mod.rs
- era-compiler-solidity/tests/cli/optimization.rs
- era-compiler-solidity/tests/cli/output_dir.rs
- era-compiler-solidity/tests/cli/solc.rs
- era-compiler-solidity/tests/cli/standard_json.rs
- era-compiler-solidity/tests/cli/yul.rs
- era-compiler-solidity/tests/cli_tests.rs
- era-compiler-solidity/tests/common/mod.rs
- era-compiler-solidity/tests/regression/factory_dependency.rs
- era-compiler-solidity/tests/regression/ir_artifacts.rs
- era-compiler-solidity/tests/regression/libraries.rs
- era-compiler-solidity/tests/regression/messages.rs
- era-compiler-solidity/tests/regression/mod.rs
- era-compiler-solidity/tests/regression/optimizer.rs
- era-compiler-solidity/tests/regression/remappings.rs
- era-compiler-solidity/tests/regression/standard_json.rs
- era-compiler-solidity/tests/regression/unsupported_instructions.rs
- era-compiler-solidity/tests/regression_tests.rs
`cargo test` by default runs each test crate (i.e. file in the `tests` directory in this case) sequentially. We get a significant speedup if we group the tests into fewer files. In this case, instead of 15 seconds, we go down to 2.5.
> test: optimize parallel regression tests execution

- .github/workflows/dependencies.yaml
Add initial WIP PoC workflow that can be triggered by dependencies to test VS `zksolc`.
It is required to be in the `main` default branch to be tested for the first time. The code is just PoC and is only for testing purposes.
> ci: add cross-dependency testing PoC workflow

- .github/workflows/dependencies.yaml
- Cargo.lock
- era-compiler-solidity/Cargo.toml
- era-compiler-solidity/tests/common/mod.rs
Rename solc_downloader to era_compiler_downloader.
Fix after common repo update.
> fix: rename solc_downloader to era_compiler_downloader

- era-compiler-solidity/src/message_type.rs
- era-compiler-solidity/tests/cli/mod.rs
- era-compiler-solidity/tests/cli/standard_json.rs
- era-compiler-solidity/tests/examples/standard_json_input/contract_incorrect_suppressed_warnings_and_errors.json
- era-compiler-solidity/tests/examples/standard_json_input/contract_suppressed_warnings_and_errors.json
This PR fixes the deserialisation of suppressed warnings and errors according to the error message in https://github.com/matter-labs/era-compiler-solidity/blob/4f20b3e6d220975cae4344c481ee1a5ffd87aa37/era-compiler-solidity/src/solc/standard_json/output/error/mod.rs#L157-L173
I was trying to compile a contract, and then I stumbled upon this error:
```
Learn more about reentrancy at https://docs.soliditylang.org/en/latest/security-considerations.html#reentrancy
You may disable this error with:
1. `suppressedErrors = ["sendtransfer"]` in standard JSON.
2. `--suppress-errors sendtransfer` in the CLI.
--> contracts/Safe.sol:243:19
```
I thought it was not a big deal, so I specified:
```
suppressedErrors: ["sendtransfer"]
```
In my standard JSON input. But then I got another error:
```
Error: …
```
> fix: correctly deserialize suppressed_warnings and suppressed-errors from standard json input

- .github/actions/install-solc/action.yml
- CHANGELOG.md
- era-compiler-solidity/src/solc/mod.rs
- era-compiler-solidity/tests/solc-bin.json
Adds the support for solc v0.8.27.
It was released by EF.
> feat: support solc v0.8.27

- .github/actions/build/action.yml
- .github/workflows/release.yaml
Use custom tag in binary names for manual releases instead of branch names.
To have binaries with short and beautiful names for manual pre-releases.
> ci: use custom tag in binary names for manual releases

- Cargo.lock
- era-compiler-solidity/Cargo.toml
- era-compiler-solidity/src/yul/parser/statement/expression/function_call/verbatim.rs
Adds a verbatim to return arbitrary data from the constructor.
It is needed for the EVM interpreter to return EVM bytecode from the constructor.
> feat: add a verbatim to return data from the constructor

- CHANGELOG.md
- Cargo.lock
- era-compiler-solidity/src/build_eravm/contract.rs
- era-compiler-solidity/src/build_evm/contract.rs
- era-compiler-solidity/src/process/mod.rs
- era-compiler-solidity/src/project/contract/mod.rs
- era-compiler-solidity/src/project/mod.rs
- era-compiler-solidity/tests/cli/llvm_ir.rs
- era-compiler-solidity/tests/cli/mod.rs
- era-compiler-solidity/tests/cli/output_dir.rs
Fixes the directory output for non-Solidity contracts.
Only Solidity contracts contain a semicolon in their paths.
Contracts in other languages were assumed to have a semicolon, and the output path was malformed.
> fix: output directory for non-Solidity contracts

- .github/workflows/release.yaml
Fixes the universal binary pre-release.
It was broken when switching to custom tag suffixes.
> fix: the universal binary pre-release

- .github/workflows/release.yaml
Fix universal macos binary generation during release builds.
Broken by the recent update with the proper suffix.
> ci: fix release suffix for macos universal binary

- CHANGELOG.md
- era-compiler-solidity/src/zksolc/arguments.rs
- era-compiler-solidity/src/zksolc/main.rs
- era-compiler-solidity/tests/cli/llvm_options.rs
- era-compiler-solidity/tests/cli/mod.rs
Adds more resilience to `--llvm-options` parsing, and makes `--help` more informative.
> fix: fragile LLVM options parsing

- CHANGELOG.md
- era-compiler-solidity/src/lib.rs
- era-compiler-solidity/src/zksolc/arguments.rs
- era-compiler-solidity/src/zksolc/main.rs
- era-compiler-solidity/tests/cli/mod.rs
- era-compiler-solidity/tests/cli/solc.rs
- era-compiler-solidity/tests/common/mod.rs
Fixes the `solc` default in standard JSON mode with Solidity input.
The `Option` was broken and the default was not set.
> fix: make solc visible in $PATH again

- era-compiler-solidity/tests/cli/solc.rs
Adds `solc-bin` to `$PATH`.
The default `solc` is not visible for e2e tests.
> fix: add solc to PATH in cli tests

- Cargo.lock
- era-compiler-solidity/Cargo.toml
- era-yul/Cargo.toml
Adds the revision part for semver of all dependencies.
Also, zkevm_opcode_defs has been moved to zksync-protocol monorepo.
`cargo update` will become more resilient.
> fix: set full semver for dependencies

- Cargo.lock
- era-compiler-solidity/src/evmla/ethereal_ir/function/block/element/mod.rs
- era-compiler-solidity/src/yul/parser/statement/expression/function_call/mod.rs
- era-yul/Cargo.toml
- era-yul/README.md
- era-yul/src/lib.rs
- era-yul/src/util/printer/mod.rs
- era-yul/src/yul/parser/identifier.rs
- era-yul/src/yul/parser/mod.rs
- era-yul/src/yul/parser/statement/code.rs
- era-yul/src/yul/parser/statement/expression/literal.rs
- era-yul/src/yul/parser/statement/object.rs
- era-yul/src/yul/parser/type.rs
- era-yul/src/yul/printer.rs
- era-yul/src/yul/visitor/mod.rs
- era-yul/tests/printer.rs
1. Memcpy declaration pointer order.
2. Event intrinsics argument order.
> fix: memcpy and event intrinsic argument order

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- era-compiler-solidity/src/lib.rs
- era-compiler-solidity/src/solc/mod.rs
- era-compiler-solidity/tests/cli/solc.rs
Bugfix for `solc` discovery bug with `1.5.5` in standard json mode caused by  https://github.com/matter-labs/era-compiler-solidity/commit/3b98e84df38c779128e7928ceac79da1338495e4#diff-f646ff6f8b3bf0d3732b0b590ea2da417a4a016da8f2132ba51bd9ccf521e1bcR422
`unwrap_or` fallback value is evaluated before `unwrap_or` is called, it caused issues in the case of `--standard-json` mode in use, `--solc` argument is provided, but there is no `solc` in the `PATH` available.
It is proposed to use `unwrap_or_else` to get the lazy evaluation of the fallback value.
> fix: solc discovery fallback in standard json mode

- Cargo.lock
- era-compiler-solidity/Cargo.toml
Removes the `git` reference from `zkevm_opcode_defs` dependency.
> fix: the zkevm_opcode_defs dependency

- era-compiler-solidity/src/error_type.rs
- era-compiler-solidity/src/lib.rs
- era-compiler-solidity/src/solc/mod.rs
- era-compiler-solidity/src/solc/standard_json/input/mod.rs
- era-compiler-solidity/src/solc/standard_json/input/settings/mod.rs
- era-compiler-solidity/src/solc/standard_json/output/mod.rs
- era-compiler-solidity/src/solc/standard_json/output/source.rs
- era-compiler-solidity/src/warning_type.rs
- era-compiler-solidity/src/zksolc/main.rs
- era-compiler-solidity/tests/cli/standard_json.rs
- era-compiler-solidity/tests/common/mod.rs
- era-compiler-solidity/tests/examples/standard_json_input/contract_incorrect_suppressed_warnings_and_errors.json
- era-compiler-solidity/tests/regression/messages.rs
1. Moves suppressed warnings and errors from the root of standard JSON input to `settings`.
2. Splits suppressed messages enum into warnings and errors, fixing the bug that a warning could be parsed as error, and vice versa. 
1. Toolkits (Hardhat, Foundry) are only exposing the `settings` object to users, so hacks are needed in the toolkit's sources in order to move fields to the root.
2. Anyway, suppressed warnings and errors shouldn't have been added to the root in the first place.
> fix: move suppressed messages to settings

- Cargo.lock
- era-compiler-solidity/src/evmla/ethereal_ir/function/block/element/mod.rs
- era-compiler-solidity/src/yul/parser/statement/expression/function_call/mod.rs
Supports `MCOPY` for EVM.
`MCOPY` instruction was unimplemented.
> feat(evm): support MCOPY for EVM

- .github/workflows/deploy-docs.yaml
- README.md
- docs/README.md
- docs/src/02-command-line-interface.md
Add `text` specifier for empty text sections.
To disallow [testing of these sections as Rust code](https://rust-lang.github.io/mdBook/cli/test.html#:~:text=rustdoc%20does%20test%20code%20blocks%20which%20have%20no%20language%20specified%3A) by the `mdbook test` command.
> docs: add text specifier for output to fix mdbook test

- .github/workflows/deploy-docs.yaml
- docs/book.toml
- docs/css/version-box.css
- docs/js/version-box.js
Add versioning box to `mdbook` documentation website.
To be able to dynamically switch between documentation versions.
> docs: add versioned mdbook support

- era-solc/src/standard_json/input/settings/selection/file/mod.rs
Fixes `#[serde(default)]` in `outputSelection`.
> fix: default for outputSelection

- .github/workflows/deploy-docs.yaml
Remove `main` branch trigger for docs deployment.
`latest` should point to the `latest` stable release of docs, not to main.
> ci: remove main trigger for docs deployment

- .github/workflows/release.yaml
Check LLVM.lock branch corresponds to semver before releasing.
To make sure LLVM version is pinned to LLVM backend release instead of main.
> ci: check that LLVM branch corresponds to semver before releasing

- docs/src/guides/01-sanitizers.md
Update sanitizers guide with symbolizer and build type.
To improve info about sanitizers builds in docs.
> docs: update sanitizers guide with symbolizer and build type

- .github/workflows/test.yaml
- deny.toml
To fix cargo deny license warnings and errors and make sure `required` check condition is always fullfilled.
> ci: update cargo deny config and enable PR tests for all files

- .github/pull_request_template.md
- CHANGELOG.md
- Cargo.lock
Cleares return data after calling `CREATE`/`CREATE2` (`ContractDeployer` system contract for EraVM).
It is cleared on EVM, but not on EraVM.
> fix(eravm): resets return data after calling CREATE

- .github/workflows/ccache-regen.yaml
It was regenerated by `cargo-check` job which is only Linux-compatible. Moved cache regeneration to unit tests in https://github.com/matter-labs/era-compiler-ci/pull/49 and updating workflow.
> ci: fix rust cache regeneration

- .github/workflows/deploy-docs.yaml
Remove pr-checks from docs.
To fix required checks for PRs containing docs and src changes.
> ci: remove pr-checks from docs to fix required checks

- era-compiler-solidity/src/evmla/ethereal_ir/function/block/element/mod.rs
The support for it was missing, leading to failures or constructors with args, including ERC20.
> fix(evm): supports EVMLA PUSHSIZE

- era-solc/src/solc.rs
- era-solc/src/standard_json/output/mod.rs
Do not prune the `evm` object from standard JSON output.
It is required for upgradable Hardhat plugin.
> fix: do not prune the evm object

- CHANGELOG.md
- Cargo.lock
- era-compiler-solidity/Cargo.toml
Removes the branch replacing call(0x04) with memcopy.
> fix: remove the branch replacing call(0x04) with memcopy

- CHANGELOG.md
- era-compiler-solidity/tests/cli/codegen.rs
- era-compiler-solidity/tests/cli/force_evmla.rs
- era-compiler-solidity/tests/common/const.rs
- era-compiler-solidity/tests/data/standard_json_input/solidity_zksolc_force_evmla.json
- era-solc/src/solc.rs
Adds warnings for `forceEVMLA` and `codegen` in standard JSON.
The former is deprecated, whereas the latter will be made mandatory in future versions.
> feat: add warnings for codegen in standard JSON

- .github/workflows/deploy-docs.yaml
Add `v` prefix to documentation website url.
To make docs url more beautiful `/v1.5.8` instead of `/1.5.8`.
> chore: add v prefix to documentation website url

- era-compiler-solidity/src/zksolc/main.rs
- era-compiler-solidity/tests/cli/mod.rs
- era-compiler-solidity/tests/cli/target.rs
- era-solc/src/solc.rs
- era-solc/src/standard_json/input/settings/mod.rs
1. Fixes the false-positive warning with `--force-evmla` with basic CLI.
2. Adds a warning that `--target evm` is WIP.
> feat: fix existing and add more warnings

- era-compiler-solidity/build.rs
Right above this comment, in the comment at the header of the file, the sentence is repeated, so their is no need for it to exist twice.
> chore: remove redundant comment

- .github/workflows/release.yaml
Add compiler binaries [GitHub attestations ](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds)support.
It would allow binary users to use attestation information through `gh api` to check if compiler binaries were built in our repositories and by our workflows improving usage security.
Attestation example: https://github.com/matter-labs/era-compiler-solidity/attestations/4282238
> ci: add binaries attestation support

- CHANGELOG.md
- docs/src/03-standard-json.md
- docs/src/04-combined-json.md
- era-compiler-solidity/tests/cli/eravm/suppress_errors.rs
- era-compiler-solidity/tests/unit/messages.rs
- era-solc/src/standard_json/input/settings/error_type.rs
- era-solc/src/standard_json/output/error/mod.rs
- era-solc/src/standard_json/output/source.rs
Prohibits the use of CREATE[2] in assembly blocks.
Fixes https://github.com/matter-labs/era-compiler-solidity/issues/239 to some extent.
It does not work with bytecode, and silently produces invalid bytecode.
> fix: prohibited the use of CREATE[2] in assembly blocks

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/src/02-command-line-interface.md
- era-compiler-solidity/tests/cli/eravm/suppress_errors.rs
- era-compiler-solidity/tests/cli/eravm/suppress_warnings.rs
- era-compiler-solidity/tests/unit/messages.rs
- era-solc/src/standard_json/input/settings/error_type.rs
- era-solc/src/standard_json/input/settings/warning_type.rs
- era-solc/src/standard_json/output/error/mod.rs
- era-solc/src/standard_json/output/source.rs
Changes the `create`/`create2` in assembly error to a warning.
It is not possible to compiler openzeppelin and forge-std with this error.
> fix: change the assembly-CREATE error to a warning

- CHANGELOG.md
- era-compiler-solidity/src/yul/parser/statement/expression/literal.rs
Fixes Windows new line characters in Yul string literals.
```
"jsdjsjdjd\
12312\\/\"\x12\u220E"
```
Literals such as the one above have been parsed incorrectly, resulting in `\r\n` bytes spilled into the constant value.
> fix: new line characters in Yul string literals on Windows

- era-compiler-solidity/src/yul/parser/statement/expression/literal.rs
Removes platform checks for Yul string literals.
It is possible to have CRLF-encoded files on Linux, and the other way around.
> fix: remove platform checks for Yul string literals

- docs/src/03-standard-json.md
- era-solc/src/standard_json/input/settings/metadata.rs
Fixes the incorrect name of metadata hash type field in standard JSON input.
> fix(docs): metadata.bytecodeHash -> metadata.hashType

- CHANGELOG.md
- era-compiler-solidity/tests/cli/codegen.rs
- era-solc/src/solc.rs
Makes the codegen warning more informative.
It was not clear to users how to fix it, and what is it about at all.
Fixes https://github.com/matter-labs/era-compiler-solidity/issues/272
> fix(eravm): make the codegen warning more informative

- docs/src/02-command-line-interface.md
I corrected a typo where "diagnostics" was used incorrectly.
It should be "diagnostic" as it is intended as an adjective in this context.
> docs: fixed typo in "diagnostics" to "diagnostic"

- docs/src/guides/01-sanitizers.md
A grammar issue in the docs: "is the feature" → "is a feature."
This fix makes the sentence more natural.
> docs: Fix minor grammar mistake in documentation

- Cargo.lock
- era-compiler-solidity/src/build_evm/contract/mod.rs
- era-compiler-solidity/src/build_evm/contract/object.rs
- era-compiler-solidity/src/build_evm/contract/runtime_build.rs
- era-compiler-solidity/src/build_evm/mod.rs
- era-compiler-solidity/src/evmla/assembly/mod.rs
- era-compiler-solidity/src/evmla/ethereal_ir/function/block/element/mod.rs
- era-compiler-solidity/src/process/mod.rs
- era-compiler-solidity/src/project/contract/ir/evmla.rs
- era-compiler-solidity/src/project/contract/ir/yul.rs
- era-compiler-solidity/src/project/contract/mod.rs
- era-compiler-solidity/src/yul/parser/statement/expression/function_call/mod.rs
- era-compiler-solidity/tests/unit/linker.rs
- era-solc/src/standard_json/output/contract/evm/mod.rs
- era-yul/src/lib.rs
- era-yul/src/yul/dependencies.rs
- era-yul/src/yul/mod.rs
- era-yul/src/yul/parser/statement/assignment.rs
- era-yul/src/yul/parser/statement/block.rs
- era-yul/src/yul/parser/statement/code.rs
- era-yul/src/yul/parser/statement/expression/function_call/mod.rs
- era-yul/src/yul/parser/statement/expression/mod.rs
- era-yul/src/yul/parser/statement/for_loop.rs
- era-yul/src/yul/parser/statement/function_definition.rs
- era-yul/src/yul/parser/statement/if_conditional.rs
- era-yul/src/yul/parser/statement/mod.rs
- era-yul/src/yul/parser/statement/object.rs
- era-yul/src/yul/parser/statement/switch/case.rs
- era-yul/src/yul/parser/statement/switch/mod.rs
- era-yul/src/yul/parser/statement/variable_declaration.rs
Supports CREATE-dependencies in the EVM target.
> feat(evm): dependencies

- docs/src/eravm/06-extensions.md
the Yul example should use `versioned_hash` instead of `input_data`. The corrected Yul example would look like this:
```solidity
assembly {
let return_value := verbatim_2i_01("decommit", versioned_hash, ergs)
}
```
> docs: fix Yul example to match pseudocode and Solidity usage

- CHANGELOG.md
- Cargo.lock
- era-compiler-solidity/src/project/contract/mod.rs
- rust-toolchain.toml
1. Enables falling back to -Oz if the EVM runtime bytecode size is exceeded.
2. Enables the check for EVM runtime bytecode size of 24576 bytes.
> feat: enable fallback-Oz and check runtime code size

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- era-compiler-solidity/src/process/mod.rs
- era-compiler-solidity/src/zksolc/arguments.rs
- era-compiler-solidity/tests/cli/recursive_process.rs
- era-solc/src/standard_json/input/mod.rs
A warning about using `suppressWarnings` in standard JSON root is printed even when the standard JSON mode is not used.
> fix: false-positive warning on error suppression

- CHANGELOG.md
- era-compiler-solidity/src/const.rs
- era-compiler-solidity/src/process/mod.rs
- era-compiler-solidity/src/zksolc/main.rs
Fixes the stack limit that was regressed during migration to one-process-per-translation-unit approach.
> fix: sets the stack limit back to 64 MB

- .github/workflows/deploy-docs.yaml
- .github/workflows/release.yaml
Default `GITHUB_TOKEN` does not trigger any workflows for release generation. As we shouldn't use any private tokens, try to use `workflow_call` to trigger documentation update.
> ci: deploy documentation after successful release by workflow call

- .github/workflows/release.yaml
Remove semver condition check for releases.
To allow use `main` branch for LLVM submodule.
> ci: remove semver condition for submodules during releases

- era-compiler-solidity/tests/scripts/solc_exit_code_failed.bat
- era-compiler-solidity/tests/scripts/solc_exit_code_failed.sh
- era-compiler-solidity/tests/scripts/solc_invalid_output_json.bat
- era-compiler-solidity/tests/scripts/solc_invalid_output_json.sh
- era-compiler-solidity/tests/scripts/solc_version_too_new.bat
- era-compiler-solidity/tests/scripts/solc_version_too_new.sh
- era-compiler-solidity/tests/scripts/solc_version_too_old.bat
- era-compiler-solidity/tests/scripts/solc_version_too_old.sh
- era-compiler-solidity/tests/solc-bin.json
- era-compiler-solidity/tests/unit/factory_dependency.rs
- era-compiler-solidity/tests/unit/ir_artifacts.rs
- era-compiler-solidity/tests/unit/libraries.rs
- era-compiler-solidity/tests/unit/linker.rs
- era-compiler-solidity/tests/unit/messages.rs
- era-compiler-solidity/tests/unit/optimizer.rs
- era-compiler-solidity/tests/unit/remappings.rs
- era-compiler-solidity/tests/unit/unsupported_instructions.rs
Bumps solc revision to v1.0.2.
It has just been released.
> chore: bump solc revision to v1.0.2
